### ISSUE TITLE
Enhancing Repo Organization: Categorizing Papers by Focus and Release Date

### ISSUE THREAD

**Issue by RunsenXu** [ActiveVisionLab/Awesome-LLM-3D#10]
Hi,

Thanks for your efforts in maintaining this repository.

I wanted to suggest a slight tweak regarding the categorization of papers. I've noticed some papers aren't directly about LLMs but more about foundation models like CLIP, such as OpenScene and LERF. My idea is to create a separate list for these types of papers. For the LLM-3D section, we could focus on papers closely related to LLMs, like those involving LLaMA.

I realize it's not always straightforward to separate these papers into distinct categories, but I think it could help make the repo more organized and user-friendly.

Also, it might be useful to list the papers in chronological order based on their release dates. This way, we can better track the field's progress.

What do you think?

**Comment by xianzhengma** [comment]
Hi Runsen,

Thanks for your suggestion. I totally agree with you. We need to create a separate list for OpenScene and LERF, for a better organization. I will do it right now!

As for using the chronological order, I think we can start from LLM-3D section. Would you like to contribute to this part?

Xianzheng

**Comment by RunsenXu** [comment]
Yes. I can do this in these few days. I think it's really necessary to maintain a separate list for papers like OpenScene, OpenMask3D, ScanNet200, Set Abstraction, etc. Of course, they are papers in this "big model era", but not typically "LLM-based" papers. For "LLM-based" papers, they usually came out post-ChatGPT, or at least used GPT-3.

Maybe maintain another list named "3D Understanding (Foundation Models)", which contains papers based on CLIP, SAM.
