### ISSUE TITLE
Add MiniGPT-3D  and GreenPLM,  thanks

### ISSUE THREAD

**Issue by TangYuan96** [ActiveVisionLab/Awesome-LLM-3D#22]
Thanks for compiling such a outstanding 3D-LLM list. Thanks for your efforts in maintaining this repository.

We have two related works that we hope to add to your awesome repository~

**MiniGPT-3D**

**time:** 2024.05.02
**Institute (first):** HUST
**Publication：** ACM MM 2024
**arXiv**： https://arxiv.org/pdf/2405.01413
**github:** https://github.com/tangyuan96/minigpt-3d
**description:**  MiniGPT-3D takes the first step in efficient 3D-LLM, training with 47.8M learnable parameters in just 26.8 hours on a single RTX 3090 GPU!

**GreenPLM**

**time:** 2024.08.28
**Institute (first):** HUST
**arXiv：** https://arxiv.org/pdf/2408.15966
**github:** https://github.com/TangYuan96/GreenPLM
**description:**  GreenPLM expands the text space to reduce the need for 3D-text pair data. GreenPLM achieves strong 3D understanding using just 12% of the 3D data or even with text-only data!

Thanks again!!

**Comment by xianzhengma** [comment]
Hi, they are cool and related works, I will add them to the list soon.

**Comment by TangYuan96** [comment]
I have provided one [PR](https://github.com/ActiveVisionLab/Awesome-LLM-3D/pull/25#issue-2519118728) for this, you can directly merge it!!

Thanks for you!!

**Comment by xianzhengma** [comment]
Hi, Yuan, thanks for your contribution! I have already merged this PR. 
In the next two weeks, I will be updating a new version of our survey paper and will consider including both of your works. I might check with you at that time. If it's convenient, feel free to add me on WeChat: mxz1997112.
