### ISSUE TITLE
Adding LLaVA-3D into your awesome repo!

### ISSUE THREAD

**Issue by ZCMax** [ActiveVisionLab/Awesome-LLM-3D#29]
Thanks for compiling such a outstanding 3D-LLM list. Thanks for your efforts in maintaining this repository.

We have one related work that we hope to add to your awesome repository~

LLaVA-3D

time: 2024.09.26
Institute (first): HKU
arXiv： https://arxiv.org/pdf/2409.18125
github: https://github.com/ZCMax/LLaVA-3D
description: LLaVA-3D: A Simple yet Effective Pathway to Empowering LMMs with 3D-awareness

**Comment by xianzhengma** [comment]
Hi Chenming,

LLaVA-3D is a highly relevant work, and its results are impressive! If possible, you can submit a PR directly, and I will merge it afterward. 

Additionally, I would like to include it in our survey paper. If you're convenient, could you add me on WeChat (ID: mxz1997112)? After I finish adding it, we can check it together.

**Comment by ZCMax** [comment]
Sorry, but could you please add me to the collaborators so that I could submit a PR~
