### ISSUE TITLE
Adding LLaNA to your survey

### ISSUE THREAD

**Issue by AndreAmaduzzi** [ActiveVisionLab/Awesome-LLM-3D#34]
Thanks for compiling this 3D-LLM list! Thanks for your efforts in maintaining this repository.

We have one related work that we hope to add to your awesome repository and survey

LLaNA

arXiv：https://arxiv.org/pdf/2406.11840
github: https://andreamaduzzi.github.io/llana/

**Comment by xianzhengma** [comment]
Hi Andrea, thanks for your kind words! LLaNA is indeed highly relevant and is the first work to combine NeRF with LLMs. I'll be sure to cite this paper in the next version of our survey.

Could you please submit a PR to the repository? That way, I can directly merge it.
