### ISSUE TITLE
A comprehensive 3D instruction-following dataset and benchmark

### ISSUE THREAD

**Issue by MSheng-Lee** [ActiveVisionLab/Awesome-LLM-3D#6]
Thanks for the curated list of 3D LLMs. We have a related work that we hope is added to this awesome repository.

M3DBench: Let's Instruct Large Models with Multi-modal 3D Prompts

Project Page: https://m3dbench.github.io/

Github: https://github.com/OpenM3D/M3DBench

Arxiv Link: https://arxiv.org/abs/2312.10763

**Comment by xianzhengma** [comment]
Thanks a lot! I have added it to the list.
